export const categoryLabels: Record<string, string> = {
    'side-dishes': 'Гарниры',
    snacks: 'Закуски',
    vegan: 'Веганская кухня',
    'second-dish': 'Вторые блюда',
    national: 'Национальные',
    salads: 'Салаты',
    'warm-snacks': 'Тёплые закуски',
    vegetables: 'Овощные',
    'poultry-dish': 'Из птицы',
    italian: 'Итальянская кухня',
    desserts: 'Десерты',
    'first-dish': 'Первые блюда',
    bakery: 'Выпечка',
    raw: 'Сыроедческие блюда',
    drinks: 'Напитки',
    'desserts-baking': 'Десерты, выпечка',
    'grilled-dishes': 'Блюда на гриле',
    'childrens-dishes': 'Детские блюда',
    'healthy-food': 'Лечебное питание',
    sauces: 'Соусы',
    preserves: 'Заготовки',
    'best-recipes': 'Самое сочное',
};
