export const subcategoriesLabels: Record<string, string> = {
    snacks: 'Закуски',
    'meat-salads': 'Мясные салаты',
    'fish-salads': 'Рыбные салаты',
    'vegetable-salads': 'Овощные салаты',
    'warm-salads': 'Тёплые салаты',
    'meat-snacks': 'Мясные закуски',
    'fish-snacks': 'Рыбные закуски',
    'vegetable-snacks': 'Овощные закуски',
    'warm-snacks': 'Тёплые закуски',
    sandwiches: 'Бутерброды',
    'fast-food': 'Фастфуд',
    'meat-soups': 'Мясные супы',
    'vegetable-soups': 'Овощные супы',
    broths: 'Бульоны',
    'cold-soups': 'Холодные супы',
    'diet-soups': 'Диетические супы',
    meat: 'Мясные',
    fish: 'Рыбные',
    vegetables: 'Овощные',
    'poultry-dish': 'Из птицы',
    'mushroom-dishes': 'Из грибов',
    'offal-dishes': 'Из субпродуктов',
    steamed: 'На пару',
    dumplings: 'Пельмени, вареники',
    'flour-side-dishes': 'Мучные гарниры',
    'vegetable-side-dishes': 'Овощные гарниры',
    pancakes: 'Блины и оладьи',
    'pies-and-donuts': 'Пироги и пончики',
    muffins: 'Кексы и маффины',
    'cheese-pancakes': 'Сырники и ватрушки',
    'puff-pastry': 'Из слоёного теста',
    'choux-pastry': 'Из заварного теста',
    'yeast-dough': 'Из дрожжевого теста',
    buns: 'Булочки и сдоба',
    'pizza-dough': 'Тесто на пиццу',
    beef: 'Говядина',
    pork: 'Свинина',
    'first-dish': 'Первые блюда',
    'second-dish': 'Вторые блюда',
    'side-dishes': 'Гарниры',
    desserts: 'Десерты',
    baking: 'Выпечка',
    raw: 'Сыроедческие блюда',
    drinks: 'Напитки',
    'gluten-free': 'Без глютена',
    'sugar-free': 'Без сахара',
    'allergen-free': 'Без аллергенов',
    'baby-food': 'Блюда для прикорма',
    'childrens-diet': 'Детская диета',
    'diet-1': 'Диета №1',
    'diet-2': 'Диета №2',
    'diet-3': 'Диета №3',
    'diet-5': 'Диета №5',
    'diet-6': 'Диета №6',
    'diet-7': 'Диета №7',
    'diet-8': 'Диета №8',
    'diet-9': 'Диета №9',
    'diet-10': 'Диета №10',
    'diet-11': 'Диета №11',
    'diet-12': 'Диета №12',
    'diet-13': 'Диета №13',
    'diet-14': 'Диета №14',
    'american-cuisine': 'Американская кухня',
    'armenian-cuisine': 'Армянская кухня',
    'greek-cuisine': 'Греческая кухня',
    'georgian-cuisine': 'Грузинская кухня',
    italian: 'Итальянская кухня',
    spanish: 'Испанская кухня',
    chinese: 'Китайская кухня',
    mexican: 'Мексиканская кухня',
    panasian: 'Паназиатская кухня',
    russian: 'Русская кухня',
    turkish: 'Турецкая кухня',
    french: 'Французская кухня',
    'swedish-': 'Шведская кухня',
    japanese: 'Японская кухня',
    'other-cuisine': 'Другая кухня',
    'meat-sauces': 'Соусы мясные',
    'cheese-sauces': 'Соусы сырные',
    marinades: 'Маринады',
    juices: 'Соки и фреши',
    compotes: 'Компоты',
    'herbal-tea': 'Лечебный чай',
    cocktails: 'Коктейли',
    'alcoholic-drinks': 'Алкогольные напитки',
    'meat-preserves': 'Мясные заготовки',
    'fish-preserves': 'Рыбные заготовки',
    'cucumber-preserves': 'Из огурцов',
    'tomato-preserves': 'Из томатов',
    'mushroom-preserves': 'Из грибов',
    'vegetable-preserves': 'Овощные заготовки',
    'salads-and-caviar': 'Салаты, икра',
    'fruit-preserves': 'Из фруктов и ягод',
};
